Repository openmediavault/openmediavault, pull requests merged in 2019-05, with the labels that each got.

#362 Display 'Updates available' status in dashboard widget.
  deb/openmediavault/debian/changelog
  deb/openmediavault/usr/share/openmediavault/engined/rpc/apt.inc
  deb/openmediavault/usr/share/openmediavault/engined/rpc/system.inc
  deb/openmediavault/usr/share/php/openmediavault/system/system.inc
  deb/openmediavault/var/www/openmediavault/js/omv/module/admin/dashboard/view/SysInfo.js
Labels: 5.x, feature

#365 Various improvements
  deb/openmediavault/debian/changelog
  deb/openmediavault/etc/cron.daily/openmediavault-mdadm
  deb/openmediavault/srv/salt/omv/deploy/mdadm/default.sls
  deb/openmediavault/srv/salt/omv/deploy/mdadm/files/etc-mdadm-mdadm.conf.j2
Labels: 5.x

#366 Fix rsyncd issue.
  deb/openmediavault/debian/changelog
  deb/openmediavault/srv/salt/omv/deploy/rsyncd/default.sls
Labels: 5.x, bugfix

#367 Enable TLS 1.3 in WebGUI
  deb/openmediavault/srv/salt/omv/deploy/nginx/files/security.conf.j2
Labels: 5.x, enhancement

#369 Adapt power management to systemd
  deb/openmediavault/debian/control
  deb/openmediavault/usr/share/openmediavault/engined/rpc/powermgmt.inc
Labels: 5.x, cleanup, enhancement

#372 Fix standby issue
  deb/openmediavault/debian/openmediavault.install
  deb/openmediavault/usr/lib/systemd/system-sleep/openmediavault-watchdog
Labels: 5.x, bugfix

#376 Issue #374: Fix iptables issue. Use systemd service instead of ifupdown.
  deb/openmediavault/debian/changelog
  deb/openmediavault/srv/salt/omv/deploy/iptables/10firewall.sls
  deb/openmediavault/srv/salt/omv/deploy/iptables/files/etc_iptables_openmediavault-firewall.j2
  deb/openmediavault/srv/salt/omv/deploy/iptables/files/ifupdown.j2
Labels: 5.x, bugfix

#385 Cleanup NFS config options
  deb/openmediavault/srv/salt/omv/deploy/nfs/files/etc-default-nfs-kernel-server.j2
  deb/openmediavault/usr/share/openmediavault/confdb/migrations.d/conf_5.0.3.sh
  deb/openmediavault/usr/share/openmediavault/datamodels/conf.service.nfs.json
  deb/openmediavault/usr/share/openmediavault/datamodels/rpc.nfs.json
  deb/openmediavault/var/www/openmediavault/js/omv/module/admin/service/nfs/Settings.js
Labels: 5.x, cleanup
