Repository openmediavault/openmediavault, pull requests merged in 2020-08, with the labels that each got.

#785 Issue #784: Use UDEV over /sys to get model and vendor information.
  deb/openmediavault/debian/changelog
  deb/openmediavault/usr/share/php/openmediavault/system/storage/storagedevice.inc
Labels: 5.x, feature

#790 Also consider read-only users and groups in proftpd limits
  deb/openmediavault/srv/salt/omv/deploy/proftpd/modules/files/mod_core.j2
Labels: 5.x, bugfix

#799 Added more options for mDNS with VPN
  deb/openmediavault/srv/salt/omv/deploy/avahi/files/etc-avahi-avahi-daemon_conf.j2
Labels: 5.x, feature

#802 Quotas are not configured after creating a file system
  deb/openmediavault/debian/changelog
  deb/openmediavault/srv/salt/omv/deploy/quota/default.sls
  deb/openmediavault/srv/salt/omv/deploy/quota/init.sls
  deb/openmediavault/usr/share/openmediavault/engined/module/quota.inc
Labels: 5.x, 6.x, bugfix
