Repository openmediavault/openmediavault, pull requests merged in 2020-11, with the labels that each got.

#841 Errors fixed and various additions for Dutch translation
  deb/openmediavault/usr/share/openmediavault/locale/nl_NL/openmediavault.po
Labels: 5.x

#847 Fix locking issue in SMB recycle bin cleanup and iptables scripts.
  deb/openmediavault/debian/changelog
  deb/openmediavault/debian/openmediavault.postinst
  deb/openmediavault/srv/salt/omv/deploy/iptables/files/etc_iptables_openmediavault-firewall.j2
  deb/openmediavault/srv/salt/omv/deploy/samba/files/cron-recyclebin-script.j2
Labels: 5.x, bugfix

#843 UDEV rules must be more restrictive to only apply to disk devices
  deb/openmediavault/debian/changelog
  deb/openmediavault/etc/udev/rules.d/99-openmediavault-dev-disk-by-id.rules
Labels: 5.x, bugfix

#855 Issue #854: Fix Python import issue.
  deb/openmediavault/debian/changelog
  deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/__init__.py
  deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/config/datamodel.py
  deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/rpc.py
  deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/settings.py
  deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/util.py
  deb/openmediavault/usr/share/openmediavault/unittests/python/test_openmediavault.py
  deb/openmediavault/usr/share/openmediavault/unittests/python/test_openmediavault_util.py
Labels: 5.x, bugfix

#863 Fix string formatting for Repository
  deb/openmediavault/usr/sbin/omv-mkaptidx
Labels: 5.x, bug

#868 Disable router advertisements for static IPv6 network interfaces.
  deb/openmediavault/debian/changelog
  deb/openmediavault/srv/salt/omv/deploy/systemd-networkd/files/bond.j2
  deb/openmediavault/srv/salt/omv/deploy/systemd-networkd/files/bridge.j2
  deb/openmediavault/srv/salt/omv/deploy/systemd-networkd/files/ethernet.j2
  deb/openmediavault/srv/salt/omv/deploy/systemd-networkd/files/vlan.j2
  deb/openmediavault/srv/salt/omv/deploy/systemd-networkd/files/wifi.j2
Labels: 5.x, cleanup, feature
