Repository openmediavault/openmediavault, pull requests merged in 2020-04, with the labels that each got.

#672 Return network interface slaves as an array
  deb/openmediavault/debian/changelog
  deb/openmediavault/usr/share/openmediavault/datamodels/rpc.network.json
  deb/openmediavault/usr/share/openmediavault/engined/rpc/network.inc
  deb/openmediavault/usr/share/openmediavault/templates/config.xml
  deb/openmediavault/usr/share/php/openmediavault/functions.inc
  deb/openmediavault/usr/share/php/openmediavault/system/storage/backend/backendabstract.inc
  deb/openmediavault/var/www/openmediavault/js/omv/module/admin/system/network/Interfaces.js
Labels: 6.x, cleanup

#690 Add macaddress to support custom mtu
  deb/openmediavault/srv/salt/omv/deploy/systemd-networkd/files/ethernet.j2
  deb/openmediavault/srv/salt/omv/deploy/systemd-networkd/files/wifi.j2
Labels: 6.x, bugfix

#687 Enhance storage host driver detection.
  deb/openmediavault/debian/changelog
  deb/openmediavault/debian/control
  deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/device/plugins/sd.py
  deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/device/storage.py
  deb/openmediavault/usr/share/php/openmediavault/system/storage/backend/sd.inc
Labels: 5.x, 6.x, cleanup
