Repository openmediavault/openmediavault, pull requests merged in 2020-10, with the labels that each got.

#826 Add message_size_limit override for Postfix
  deb/openmediavault/srv/salt/omv/deploy/postfix/files/main.cf.j2
Labels: 5.x, feature

#830 Issue #829: Show the listing of directory entries to which the anonymous user normally has no access permissions.
  deb/openmediavault/debian/changelog
  deb/openmediavault/debian/openmediavault.postinst
  deb/openmediavault/srv/salt/omv/deploy/proftpd/modules/files/mod_core.j2
Labels: 5.x, 6.x, bugfix

#834 Use PHP_EOL to separate email headers.
  deb/openmediavault/usr/share/php/openmediavault/email.inc
Labels: 5.x, cleanup
