Repository openmediavault/openmediavault, pull requests merged in 2020-01, with the labels that each got.

#552 Issue #551: Fix STARTTLS issue in Postfix configuration.
  deb/openmediavault/debian/changelog
  deb/openmediavault/srv/salt/omv/deploy/postfix/files/main.cf.j2
Labels: 5.x, bugfix, needs review

#565 Issue 564: Improve openmediavault.fs.Filesystem::get_parent_devi…
  deb/openmediavault/debian/changelog
  deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/fs/__init__.py
Labels: 5.x, bugfix

#568 Issue #567: Add storage backend for Areca RAID controllers.
  deb/openmediavault/debian/changelog
  deb/openmediavault/usr/share/php/openmediavault/system/storage/backend/sd.inc
  deb/openmediavault/usr/share/php/openmediavault/system/storage/storagedevicearcmsr.inc
Labels: 5.x, feature

#577 Improve OMV\System\Filesystem\Filesystem::getImplByMountPoint()…
  deb/openmediavault/debian/changelog
  deb/openmediavault/usr/share/php/openmediavault/system/filesystem/filesystem.inc
  deb/openmediavault/usr/share/php/openmediavault/system/mountpoint.inc
Labels: 5.x, cleanup

#579 Merge pull request #579 from myomv100/master
  deb/openmediavault/usr/share/openmediavault/locale/ar_SA/openmediavault.po
  deb/openmediavault/var/www/openmediavault/js/omv/globals.js
Labels: 5.x, feature

#581 add ubuntu support
  deb/openmediavault/srv/salt/omv/deploy/apt/default.sls
  deb/openmediavault/srv/salt/omv/deploy/apt/files/etc-apt-sources_list_d-openmediavault-debian-security_list.j2
  deb/openmediavault/srv/salt/omv/deploy/apt/files/etc-apt-sources_list_d-openmediavault-kernel-backports_list.j2
  deb/openmediavault/srv/salt/omv/deploy/apt/files/etc-apt-sources_list_d-openmediavault-os-security_list.j2
Labels: 5.x
