Repository openmediavault/openmediavault, pull requests merged in 2021-02, with the labels that each got.

#960 Issue #959: Improve SMART support for HPSA HBA.
  deb/openmediavault/debian/changelog
  deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/device/plugins/sd.py
  deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/device/storage.py
  deb/openmediavault/usr/share/php/openmediavault/system/storage/backend/sd.inc
  deb/openmediavault/usr/share/php/openmediavault/system/storage/smartinformation.inc
  deb/openmediavault/usr/share/php/openmediavault/system/storage/smarttrait.inc
  deb/openmediavault/usr/share/php/openmediavault/system/storage/storagedevicehpsa.inc
  deb/openmediavault/usr/share/php/openmediavault/system/storage/storagedevicesd.inc
Labels: 5.x affected, enhancement

#962 Update to document faulty MB174U3S-4SB enclosure
  deb/openmediavault/etc/udev/rules.d/61-openmediavault-dev-disk-by-id.rules
Labels: 5.x affected, documentation

#965 Rename module to fix import issues.
  deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/collectiontools.py
  deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/config/database.py
  deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/config/object.py
  deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/device/plugins/dm.py
  deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/device/plugins/md.py
  deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/json/schema.py
  deb/openmediavault/usr/share/openmediavault/unittests/python/test_openmediavault_collections.py
Labels: 5.x affected, cleanup

#966 Rename various OMV Python modules because of import issues.
  deb/openmediavault-diskstats/debian/changelog
  deb/openmediavault-diskstats/debian/control
  deb/openmediavault-diskstats/usr/share/openmediavault/mkrrdgraph/plugins.d/disk.py
  deb/openmediavault-nut/debian/changelog
  deb/openmediavault-nut/debian/control
  deb/openmediavault-nut/usr/share/openmediavault/mkrrdgraph/plugins.d/nut.py
  deb/openmediavault/debian/changelog
  deb/openmediavault/srv/salt/_modules/omv_conf.py
  deb/openmediavault/srv/salt/_modules/omv_utils.py
  deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/__init__.py
  deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/confdbadm.py
  deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/config/datamodel.py
  deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/config/object.py
  deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/datamodel/schema.py
  deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/device/block.py
  deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/device/plugins/dm.py
  deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/device/plugins/md.py
  deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/device/storage.py
  deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/fs/__init__.py
  deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/json/schema.py
  deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/monit.py
  deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/procutils.py
  deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/settings.py
  deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/sortutils.py
  deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/stringutils.py
  deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/utils.py
  deb/openmediavault/usr/sbin/omv-env
  deb/openmediavault/usr/share/openmediavault/confdbadm/commands.d/create.py
  deb/openmediavault/usr/share/openmediavault/confdbadm/commands.d/migrate.py
  deb/openmediavault/usr/share/openmediavault/confdbadm/commands.d/populate.py
  deb/openmediavault/usr/share/openmediavault/firstaid/modules.d/10configure_network.py
  deb/openmediavault/usr/share/openmediavault/firstaid/modules.d/35reset_failed_login_attempt_counter.py
  deb/openmediavault/usr/share/openmediavault/firstaid/modules.d/40restore_config_backup.py
  deb/openmediavault/usr/share/openmediavault/firstaid/modules.d/50fix_rrd_database.py
  deb/openmediavault/usr/share/openmediavault/firstaid/modules.d/60clean_local_dpkg_repository.py
  deb/openmediavault/usr/share/openmediavault/firstaid/modules.d/65clear_webgui_cache.py
  deb/openmediavault/usr/share/openmediavault/firstaid/modules.d/70submit_sysinfo.py
  deb/openmediavault/usr/share/openmediavault/mkrrdgraph/plugins.d/cpu.py
  deb/openmediavault/usr/share/openmediavault/mkrrdgraph/plugins.d/df.py
  deb/openmediavault/usr/share/openmediavault/mkrrdgraph/plugins.d/interface.py
  deb/openmediavault/usr/share/openmediavault/mkrrdgraph/plugins.d/load.py
  deb/openmediavault/usr/share/openmediavault/mkrrdgraph/plugins.d/memory.py
  deb/openmediavault/usr/share/openmediavault/mkrrdgraph/plugins.d/uptime.py
  deb/openmediavault/usr/share/openmediavault/unittests/python/test_openmediavault_string.py
  deb/openmediavault/usr/share/openmediavault/unittests/python/test_openmediavault_subprocess.py
  deb/openmediavault/usr/share/openmediavault/unittests/python/test_openmediavault_util.py
Labels: 5.x affected, cleanup

#969 Issue #968: Configured quota is not displayed correct.
  deb/openmediavault/debian/changelog
  deb/openmediavault/var/www/openmediavault/js/omv/module/admin/storage/filesystem/Filesystem.js
Labels: 5.x affected, bug

#971 Issue #970: HPSA HBA improvements causing a regression when controller is in RAID mode
  deb/openmediavault/debian/changelog
  deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/device/plugins/sd.py
  deb/openmediavault/usr/share/openmediavault/unittests/python/test_openmediavault_device_storagedevice.py
  deb/openmediavault/usr/share/php/openmediavault/system/storage/storagedevicehpsa.inc
  deb/openmediavault/usr/share/php/openmediavault/system/storage/storagedevicesd.inc
Labels: 5.x affected, bugfix

#973 Issue #972: Read command output up to a max. number of bytes to do not run into resource limits
  deb/openmediavault/debian/changelog
  deb/openmediavault/usr/share/openmediavault/datamodels/rpc.exec.json
  deb/openmediavault/usr/share/openmediavault/engined/rpc/exec.inc
  deb/openmediavault/var/www/openmediavault/js/omv/window/Execute.js
Labels: 5.x affected, bugfix
