Repository openmediavault/openmediavault, pull requests merged in 2021-11, with the labels that each got.

#1128 Issue #1127: Support ed25519 SSH public keys in the user settings dialog
  deb/openmediavault/debian/changelog
  deb/openmediavault/usr/share/php/openmediavault/ssh/publickey.inc
  deb/openmediavault/workbench/src/app/shared/forms/custom-validators.ts
Labels: feature, 6.x

#1135 Update etc-exports.j2
  deb/openmediavault/srv/salt/omv/deploy/nfs/files/etc-exports.j2
Labels: bugfix, 6.x

#1136 Display the shared folder comment if available, otherwise the disk and the relative path
  deb/openmediavault/usr/share/openmediavault/engined/rpc/sharemgmt.inc
Labels: enhancement, 6.x

#1140 Fix lock file issue in SMB recycle script.
  deb/openmediavault/srv/salt/omv/deploy/samba/files/cron-recyclebin-script.j2
Labels: bugfix, 6.x

#1146 Enhance the remote filter capability.
  deb/openmediavault/usr/share/openmediavault/datamodels/rpc.common.json
  deb/openmediavault/usr/share/openmediavault/engined/rpc/pluginmgmt.inc
  deb/openmediavault/usr/share/php/openmediavault/rpc/serviceabstract.inc
  deb/openmediavault/workbench/src/app/core/components/intuition/datatable-page/datatable-page.component.html
  deb/openmediavault/workbench/src/app/core/components/intuition/datatable-page/datatable-page.component.ts
  deb/openmediavault/workbench/src/app/core/components/intuition/models/datatable-page-config.type.ts
  deb/openmediavault/workbench/src/app/pages/system/plugins/plugins-datatable-page.component.ts
  deb/openmediavault/workbench/src/app/shared/components/datatable/datatable.component.html
  deb/openmediavault/workbench/src/app/shared/components/datatable/datatable.component.ts
Labels: enhancement, 6.x
