Repository openmediavault/openmediavault, pull requests merged in 2021-03, with the labels that each got.

#974 Issue #972: UI crashes when backend sends too much data in the 'Execute' dialog.
  deb/openmediavault/debian/changelog
  deb/openmediavault/var/www/openmediavault/js/omv/window/Execute.js
Labels: 5.x affected, cleanup

#976 Isse #975: Improve handling of blanks in user/group names in the ACL dialog
  deb/openmediavault/debian/changelog
  deb/openmediavault/usr/share/openmediavault/engined/rpc/sharemgmt.inc
  deb/openmediavault/usr/share/php/openmediavault/functions.inc
Labels: 5.x affected, bugfix, enhancement

#982 Install security updates automatically.
  deb/openmediavault/debian/changelog
  deb/openmediavault/debian/openmediavault.postinst
  deb/openmediavault/srv/salt/omv/deploy/apt/default.sls
  deb/openmediavault/srv/salt/omv/deploy/apt/files/etc-apt-sources_list_d-openmediavault-os-security_list.j2
  deb/openmediavault/srv/salt/omv/deploy/cronapt/default.sls
  deb/openmediavault/srv/salt/omv/deploy/cronapt/files/etc_cron-apt_mailmsgd_3-download.j2
  deb/openmediavault/srv/salt/omv/deploy/cronapt/files/etc_cron-apt_mailmsgd_5-openmediavault-security.j2
Labels: 5.x affected, enhancement

#990 "is selecting" -> "is selected" - small grammar change to read better in english
  deb/openmediavault/usr/share/openmediavault/locale/ar_SA/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/bg_BG/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/ca_ES/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/cs_CZ/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/da_DA/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/de_DE/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/el_GR/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/es_ES/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/fr_FR/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/gl_ES/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/hu_HU/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/it_IT/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/ja_JP/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/ko_KR/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/nl_NL/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/no_NO/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/openmediavault.pot
  deb/openmediavault/usr/share/openmediavault/locale/pl_PL/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/pt_PT/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/ru_RU/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/sl_SI/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/sv_SV/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/tr_TR/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/uk_UK/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/zh_CN/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/zh_TW/openmediavault.po
  deb/openmediavault/var/www/openmediavault/js/omv/module/admin/service/smb/Shares.js
Labels: 5.x affected, 6.x affected, bugfix
