Repository openmediavault/openmediavault, pull requests merged in 2021-04, with the labels that each got.

#999 Refactor file system management.
  deb/openmediavault/debian/changelog
  deb/openmediavault/srv/salt/omv/deploy/monit/services/files/filesystem.j2
  deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/fs/__init__.py
  deb/openmediavault/usr/share/openmediavault/confdb/migrations.d/conf_6.0.0.sh
  deb/openmediavault/usr/share/openmediavault/datamodels/conf.system.filesystem.mountpoint.json
  deb/openmediavault/usr/share/openmediavault/datamodels/rpc.filesystemmgmt.json
  deb/openmediavault/usr/share/openmediavault/datamodels/rpc.fstab.json
  deb/openmediavault/usr/share/openmediavault/engined/rpc/filesystemmgmt.inc
  deb/openmediavault/usr/share/openmediavault/engined/rpc/fstab.inc
  deb/openmediavault/usr/share/openmediavault/engined/rpc/sharemgmt.inc
  deb/openmediavault/usr/share/openmediavault/templates/config.xml
  deb/openmediavault/usr/share/openmediavault/workbench/dashboard.d/file_systems.yaml
  deb/openmediavault/usr/share/php/openmediavault/system/filesystem/btrfs.inc
  deb/openmediavault/usr/share/php/openmediavault/system/filesystem/filesystem.inc
  deb/openmediavault/usr/share/php/openmediavault/system/mountpoint.inc
  deb/openmediavault/workbench/src/app/core/components/dashboard/widgets/widget-filesystems-status/widget-filesystems-status.component.html
  deb/openmediavault/workbench/src/app/core/components/limn-ui/datatable-page/datatable-page.component.ts
  deb/openmediavault/workbench/src/app/core/components/limn-ui/form-page/form-page.component.ts
  deb/openmediavault/workbench/src/app/core/components/limn-ui/models/datatable-page-action-config.type.ts
  deb/openmediavault/workbench/src/app/core/components/limn-ui/models/form-page-config.type.ts
  deb/openmediavault/workbench/src/app/pages/storage/filesystems/filesystem-create-form-page.component.ts
  deb/openmediavault/workbench/src/app/pages/storage/filesystems/filesystem-datatable-page.component.ts
  deb/openmediavault/workbench/src/app/pages/storage/filesystems/filesystem-mount-form-page.component.ts
  deb/openmediavault/workbench/src/app/pages/storage/shared-folders/shared-folder-form-page.component.ts
  deb/openmediavault/workbench/src/app/pages/storage/storage-routing.module.ts
  deb/openmediavault/workbench/src/app/pages/storage/storage.module.ts
  deb/openmediavault/workbench/src/app/shared/components/datatable/datatable.component.html
  deb/openmediavault/workbench/src/app/shared/components/progress-bar/progress-bar.component.html
  deb/openmediavault/workbench/src/app/shared/components/task-dialog/task-dialog.component.ts
  deb/openmediavault/workbench/src/app/shared/models/task-dialog-config.type.ts
Labels: 6.x affected, enhancement

#1003 Issue #1001: Private keys of SSL certificates are not deleted.
  deb/openmediavault/debian/changelog
  deb/openmediavault/srv/salt/omv/deploy/certificates/ssl.sls
Labels: 5.x affected, 6.x affected, bug

#1005 Do not use {{ _selected[0].xyz }} for datatable actions
  deb/openmediavault-clamav/debian/changelog
  deb/openmediavault-clamav/usr/share/openmediavault/workbench/component.d/omv-services-clamav-onaccess-scan-datatable-page.yaml
  deb/openmediavault-clamav/usr/share/openmediavault/workbench/component.d/omv-services-clamav-scan-datatable-page.yaml
  deb/openmediavault-lvm2/debian/changelog
  deb/openmediavault-lvm2/usr/share/openmediavault/workbench/component.d/omv-storage-lvm-pv-datatable-page.yaml
  deb/openmediavault-lvm2/usr/share/openmediavault/workbench/component.d/omv-storage-lvm-vg-datatable-page.yaml
  deb/openmediavault-usbbackup/debian/changelog
  deb/openmediavault-usbbackup/usr/share/openmediavault/workbench/component.d/omv-services-usbbackup-job-datatable-page.yaml
  deb/openmediavault/workbench/src/app/pages/network/firewall/rules/firewall-rule-inet-datatable-page.component.ts
  deb/openmediavault/workbench/src/app/pages/network/firewall/rules/firewall-rule-inet6-datatable-page.component.ts
  deb/openmediavault/workbench/src/app/pages/network/interfaces/interface-datatable-page.component.ts
  deb/openmediavault/workbench/src/app/pages/services/ftp/ftp-ban-rule-datatable-page.component.ts
  deb/openmediavault/workbench/src/app/pages/services/ftp/ftp-share-datatable-page.component.ts
  deb/openmediavault/workbench/src/app/pages/services/nfs/nfs-share-datatable-page.component.ts
  deb/openmediavault/workbench/src/app/pages/services/rsync/rsync-module-datatable-page.component.ts
  deb/openmediavault/workbench/src/app/pages/services/rsync/rsync-task-datatable-page.component.ts
  deb/openmediavault/workbench/src/app/pages/services/smb/smb-share-datatable-page.component.ts
  deb/openmediavault/workbench/src/app/pages/storage/filesystems/filesystem-datatable-page.component.ts
  deb/openmediavault/workbench/src/app/pages/storage/md/md-datatable-page.component.ts
  deb/openmediavault/workbench/src/app/pages/storage/smart/smart-task-datatable-page.component.ts
  deb/openmediavault/workbench/src/app/pages/system/certificates/ssh/ssh-certificate-datatable-page.component.ts
  deb/openmediavault/workbench/src/app/pages/system/certificates/ssl/ssl-certificate-datatable-page.component.ts
  deb/openmediavault/workbench/src/app/pages/system/cron/cron-task-datatable-page.component.ts
  deb/openmediavault/workbench/src/app/pages/usermgmt/groups/group-datatable-page.component.ts
  deb/openmediavault/workbench/src/app/pages/usermgmt/users/user-datatable-page.component.ts
Labels: 6.x affected, bug

#1004 add code to skip adding debian-security on raspberrypi boards
  deb/openmediavault/srv/salt/omv/deploy/apt/default.sls
Labels: 5.x affected, 6.x affected, enhancement

#1008 Issue #1007: Run postfix notification scripts with dedicated user openmediavault-notify
  deb/openmediavault/debian/changelog
  deb/openmediavault/debian/openmediavault.postinst
  deb/openmediavault/srv/salt/omv/deploy/postfix/files/master.cf.j2
  deb/openmediavault/usr/share/openmediavault/notification/sink.d/README
Labels: 5.x affected, 6.x affected, enhancement

#1014 Migrate Chart.js to v3
  deb/openmediavault/usr/share/openmediavault/workbench/dashboard.d/cpu.yaml
  deb/openmediavault/usr/share/openmediavault/workbench/dashboard.d/load_avg.yaml
  deb/openmediavault/usr/share/openmediavault/workbench/dashboard.d/memory.yaml
  deb/openmediavault/workbench/package-lock.json
  deb/openmediavault/workbench/package.json
  deb/openmediavault/workbench/src/app/core/components/dashboard/models/dashboard-widget-config.model.ts
  deb/openmediavault/workbench/src/app/core/components/dashboard/widgets/widget-chart/widget-chart.component.html
  deb/openmediavault/workbench/src/app/core/components/dashboard/widgets/widget-chart/widget-chart.component.ts
Labels: 6.x affected, enhancement

#1016 Adapt module.run calls to new syntax
  deb/openmediavault-forkeddaapd/debian/changelog
  deb/openmediavault-forkeddaapd/srv/salt/omv/deploy/forked-daapd/default.sls
  deb/openmediavault-nut/debian/changelog
  deb/openmediavault-nut/srv/salt/omv/deploy/nut/default.sls
  deb/openmediavault-shairport/debian/changelog
  deb/openmediavault-shairport/srv/salt/omv/deploy/shairport-sync/default.sls
  deb/openmediavault-usbbackup/debian/changelog
  deb/openmediavault-usbbackup/srv/salt/omv/deploy/usbbackup/default.sls
  deb/openmediavault/debian/changelog
  deb/openmediavault/srv/salt/omv/deploy/apt/default.sls
  deb/openmediavault/srv/salt/omv/deploy/collectd/default.sls
  deb/openmediavault/srv/salt/omv/deploy/iptables/10firewall.sls
  deb/openmediavault/srv/salt/omv/deploy/nginx/default.sls
  deb/openmediavault/srv/salt/omv/deploy/phpfpm/default.sls
  deb/openmediavault/srv/salt/omv/deploy/proftpd/default.sls
  deb/openmediavault/srv/salt/omv/deploy/rrdcached/default.sls
  deb/openmediavault/srv/salt/omv/deploy/systemd/10sharedfolders.sls
  deb/openmediavault/srv/salt/omv/deploy/systemd/20tmp.sls
  deb/openmediavault/srv/salt/omv/refresh/default.sls
Labels: 5.x affected, 6.x affected, cleanup

#1020 Add file form field.
  deb/openmediavault/workbench/src/app/core/components/limn-ui/form/components/form-file-input/form-file-input.component.html
  deb/openmediavault/workbench/src/app/core/components/limn-ui/form/components/form-file-input/form-file-input.component.scss
  deb/openmediavault/workbench/src/app/core/components/limn-ui/form/components/form-file-input/form-file-input.component.spec.ts
  deb/openmediavault/workbench/src/app/core/components/limn-ui/form/components/form-file-input/form-file-input.component.ts
  deb/openmediavault/workbench/src/app/core/components/limn-ui/form/form.component.html
  deb/openmediavault/workbench/src/app/core/components/limn-ui/limn-ui.module.ts
  deb/openmediavault/workbench/src/app/core/components/limn-ui/models/form-field-config.type.ts
  deb/openmediavault/workbench/src/app/pages/system/certificates/ssh/ssh-certificate-import-form-page.component.ts
  deb/openmediavault/workbench/src/app/pages/system/certificates/ssl/ssl-certificate-import-form-page.component.ts
Labels: 6.x affected, enhancement
