Repository openmediavault/openmediavault, pull requests merged in 2022-06, with the labels that each got.

#1321 salt: proftpd: remove option MultilineRFC2228 by default
  deb/openmediavault/srv/salt/omv/deploy/proftpd/modules/files/mod_core.j2
Labels: bugfix, cleanup, 6.x

#1325 Issue #510: Create correct /etc/hosts if permanent IP addresses are used
  deb/openmediavault/debian/changelog
  deb/openmediavault/debian/openmediavault.postinst
  deb/openmediavault/srv/salt/omv/deploy/hosts/10default.sls
Labels: bugfix, 6.x

#1327 Add 'codeEditor' form field
  deb/openmediavault/debian/changelog
  deb/openmediavault/workbench/jest.config.js
  deb/openmediavault/workbench/package-lock.json
  deb/openmediavault/workbench/package.json
  deb/openmediavault/workbench/src/app/core/components/intuition/form/components/form-code-editor/form-code-editor.component.html
  deb/openmediavault/workbench/src/app/core/components/intuition/form/components/form-code-editor/form-code-editor.component.scss
  deb/openmediavault/workbench/src/app/core/components/intuition/form/components/form-code-editor/form-code-editor.component.spec.ts
  deb/openmediavault/workbench/src/app/core/components/intuition/form/components/form-code-editor/form-code-editor.component.ts
  deb/openmediavault/workbench/src/app/core/components/intuition/form/form.component.html
  deb/openmediavault/workbench/src/app/core/components/intuition/form/form.component.ts
  deb/openmediavault/workbench/src/app/core/components/intuition/intuition.module.ts
  deb/openmediavault/workbench/src/app/core/components/intuition/material/mat-form-code-editor/mat-form-code-editor.component.html
  deb/openmediavault/workbench/src/app/core/components/intuition/material/mat-form-code-editor/mat-form-code-editor.component.scss
  deb/openmediavault/workbench/src/app/core/components/intuition/material/mat-form-code-editor/mat-form-code-editor.component.spec.ts
  deb/openmediavault/workbench/src/app/core/components/intuition/material/mat-form-code-editor/mat-form-code-editor.component.ts
  deb/openmediavault/workbench/src/app/core/components/intuition/models/form-field-config.type.ts
Labels: enhancement, feature, 6.x
