Repository openmediavault/openmediavault, pull requests merged in 2023-12, with the labels that each got.

#1647 Add omv-release-upgrade infrastructure
  deb/openmediavault/debian/changelog
  deb/openmediavault/usr/sbin/omv-release-upgrade
  deb/openmediavault/usr/share/openmediavault/release-upgrade/post.d/10-enable-cron-apt
  deb/openmediavault/usr/share/openmediavault/release-upgrade/post.d/10-enable-omv-mkaptidx
  deb/openmediavault/usr/share/openmediavault/release-upgrade/post.d/50-set-dirty-apt
  deb/openmediavault/usr/share/openmediavault/release-upgrade/post.d/50-set-dirty-nfs
  deb/openmediavault/usr/share/openmediavault/release-upgrade/post.d/50-set-dirty-nginx
  deb/openmediavault/usr/share/openmediavault/release-upgrade/post.d/50-set-dirty-phpfpm
  deb/openmediavault/usr/share/openmediavault/release-upgrade/post.d/50-set-dirty-samba
  deb/openmediavault/usr/share/openmediavault/release-upgrade/post.d/70-deploy-config
  deb/openmediavault/usr/share/openmediavault/release-upgrade/post.d/80-apt-autoremove
  deb/openmediavault/usr/share/openmediavault/release-upgrade/post.d/90-apt-clean
  deb/openmediavault/usr/share/openmediavault/release-upgrade/post.d/95-mdadm-note
  deb/openmediavault/usr/share/openmediavault/release-upgrade/post.d/99-reboot-required
  deb/openmediavault/usr/share/openmediavault/release-upgrade/pre.d/05-install-usrmerge
  deb/openmediavault/usr/share/openmediavault/release-upgrade/pre.d/10-apt-purge-local-archive
  deb/openmediavault/usr/share/openmediavault/release-upgrade/pre.d/10-disable-cron-apt
  deb/openmediavault/usr/share/openmediavault/release-upgrade/pre.d/10-disable-omv-mkaptidx
  deb/openmediavault/usr/share/openmediavault/release-upgrade/pre.d/20-apt-remove-kernel-backports
  deb/openmediavault/usr/share/openmediavault/release-upgrade/pre.d/20-apt-update-source-list
  deb/openmediavault/usr/share/openmediavault/release-upgrade/pre.d/90-backup-config-db
Labels: enhancement, 6.x

#1650 Add UTF8 support for SSL certificates created in Web UI
  deb/openmediavault/usr/share/openmediavault/engined/rpc/certificatemgmt.inc
Labels: enhancement, 6.x, 7.x

#1653 Use the unattended-upgrades package instead on cron-apt
  deb/openmediavault/debian/changelog
  deb/openmediavault/debian/control
  deb/openmediavault/debian/openmediavault.postinst
  deb/openmediavault/etc/apt/apt.conf.d/95openmediavault-periodic
  deb/openmediavault/etc/apt/apt.conf.d/95openmediavault-unattended-upgrades
  deb/openmediavault/etc/apt/listchanges.conf.d/95openmediavault.conf
  deb/openmediavault/etc/apt/post-invoke.d/10install-cleanup
  deb/openmediavault/etc/cron.daily/openmediavault-cron-apt
  deb/openmediavault/etc/cron.daily/openmediavault-reboot_required
  deb/openmediavault/etc/systemd/system/apt-daily-upgrade.service.d/openmediavault.conf
  deb/openmediavault/etc/systemd/system/apt-daily-upgrade.timer.d/openmediavault.conf
  deb/openmediavault/etc/systemd/system/apt-daily.service.d/openmediavault.conf
  deb/openmediavault/etc/systemd/system/apt-daily.timer.d/openmediavault.conf
  deb/openmediavault/srv/salt/omv/deploy/cronapt/default.sls
  deb/openmediavault/srv/salt/omv/deploy/cronapt/files/etc_cron-apt_config.j2
  deb/openmediavault/srv/salt/omv/deploy/cronapt/files/etc_cron-apt_mailmsgd_3-download.j2
  deb/openmediavault/srv/salt/omv/deploy/cronapt/files/etc_cron-apt_mailmsgd_5-openmediavault-security.j2
  deb/openmediavault/usr/share/openmediavault/engined/module/cronapt.inc
Labels: enhancement, 7.x

#1655 Add email to SSL certificate's SAN in its own field
  deb/openmediavault/usr/share/openmediavault/engined/rpc/certificatemgmt.inc
Labels: enhancement, 7.x

#1672 Add support for hints on datatable pages
  deb/openmediavault-filebrowser/debian/changelog
  deb/openmediavault-filebrowser/usr/share/openmediavault/workbench/component.d/omv-services-filebrowser-form-page.yaml
  deb/openmediavault-onedrive/debian/changelog
  deb/openmediavault-onedrive/usr/share/openmediavault/workbench/component.d/omv-services-onedrive-form-page.yaml
  deb/openmediavault-photoprism/debian/changelog
  deb/openmediavault-photoprism/usr/share/openmediavault/workbench/component.d/omv-services-photoprism-form-page.yaml
  deb/openmediavault/usr/share/openmediavault/workbench/component.d/omv-storage-filesystem-btrfs-create-form-page.yaml
  deb/openmediavault/usr/share/openmediavault/workbench/component.d/omv-storage-filesystem-generic-create-form-page.yaml
  deb/openmediavault/workbench/src/app/core/components/intuition/abstract-page-component.ts
  deb/openmediavault/workbench/src/app/core/components/intuition/datatable-page/datatable-page.component.html
  deb/openmediavault/workbench/src/app/core/components/intuition/datatable-page/datatable-page.component.ts
  deb/openmediavault/workbench/src/app/core/components/intuition/form-page/form-page.component.html
  deb/openmediavault/workbench/src/app/core/components/intuition/form-page/form-page.component.ts
  deb/openmediavault/workbench/src/app/core/components/intuition/models/datatable-page-config.type.ts
  deb/openmediavault/workbench/src/app/core/components/intuition/models/form-page-config.type.ts
  deb/openmediavault/workbench/src/app/core/components/intuition/models/page-config.type.ts
  deb/openmediavault/workbench/src/app/pages/services/ssh/ssh-form-page.component.ts
  deb/openmediavault/workbench/src/app/pages/storage/shared-folders/shared-folder-permissions-datatable-page.component.ts
  deb/openmediavault/workbench/src/app/pages/system/certificates/ssh/ssh-certificate-datatable-page.component.ts
  deb/openmediavault/workbench/src/app/pages/usermgmt/groups/group-shared-folder-permissions-datatable-page.component.ts
  deb/openmediavault/workbench/src/app/pages/usermgmt/usermgmt-routing.module.ts
  deb/openmediavault/workbench/src/app/pages/usermgmt/users/user-shared-folder-permissions-datatable-page.component.ts
  deb/openmediavault/workbench/src/app/shared/components/alert-panel/alert-panel.component.html
  deb/openmediavault/workbench/src/app/shared/components/alert-panel/alert-panel.component.ts
Labels: 7.x
