Repository openmediavault/openmediavault, pull requests merged in 2024-12, with the labels that each got.

#1867 Issue #1865: Remove support for WPA3 authentication for wireless connections
  deb/openmediavault/debian/changelog
  deb/openmediavault/usr/share/openmediavault/firstaid/modules.d/10configure_network.py
  deb/openmediavault/workbench/src/app/pages/network/interfaces/interface-wifi-form-page.component.ts
Labels: bugfix, 7.x

#1868 Correct and clarify usermgmt.inc docs for disallowusermod setting
  deb/openmediavault/usr/share/openmediavault/engined/rpc/usermgmt.inc
Labels: bugfix, cleanup, documentation, 7.x

#1872 Add the `Follow symlinks` and `Wide links` options to SMB shares
  deb/openmediavault/debian/changelog
  deb/openmediavault/debian/openmediavault.postinst
  deb/openmediavault/srv/salt/omv/deploy/samba/files/global.j2
  deb/openmediavault/srv/salt/omv/deploy/samba/files/homes.j2
  deb/openmediavault/srv/salt/omv/deploy/samba/files/shares.j2
  deb/openmediavault/usr/share/openmediavault/confdb/migrations.d/conf_7.4.17.sh
  deb/openmediavault/usr/share/openmediavault/datamodels/conf.service.smb.json
  deb/openmediavault/usr/share/openmediavault/datamodels/conf.service.smb.share.json
  deb/openmediavault/usr/share/openmediavault/locale/ar_SA/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/bg_BG/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/ca_ES/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/cs_CZ/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/da_DA/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/de_DE/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/el_GR/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/es_ES/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/eu_ES/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/fr_FR/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/gl_ES/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/hu_HU/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/it_IT/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/ja_JP/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/ko_KR/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/nl_NL/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/no_NO/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/openmediavault.pot
  deb/openmediavault/usr/share/openmediavault/locale/pl_PL/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/pt_PT/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/ru_RU/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/sl_SI/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/sv_SV/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/tr_TR/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/uk_UK/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/zh_CN/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/locale/zh_TW/openmediavault.po
  deb/openmediavault/usr/share/openmediavault/templates/config.xml
  deb/openmediavault/workbench/src/app/pages/services/smb/smb-settings-form-page.component.ts
  deb/openmediavault/workbench/src/app/pages/services/smb/smb-share-form-page.component.ts
Labels: enhancement, 7.x

#1876 Retry failed connections 5 times before failure out
  deb/openmediavault/debian/changelog
  deb/openmediavault/workbench/src/app/pages/system/plugins/plugins-datatable-page.component.ts
  deb/openmediavault/workbench/src/app/pages/system/updates/update-datatable-page.component.ts
  deb/openmediavault/workbench/src/app/shared/components/task-dialog/task-dialog.component.ts
  deb/openmediavault/workbench/src/app/shared/models/task-dialog-config.type.ts
Labels: enhancement, 7.x
