Repository openmediavault/openmediavault, pull requests merged in 2024-08, with the labels that each got.

#1807 Rename `Disk Usage` to `File System Usage`
  deb/openmediavault/debian/changelog
  deb/openmediavault/usr/share/openmediavault/mkrrdgraph/plugins.d/df.py
  deb/openmediavault/usr/share/openmediavault/workbench/navigation.d/diagnostics.performance-statistics.df.yaml
  deb/openmediavault/usr/share/openmediavault/workbench/navigation.d/diagnostics.performance-statistics.diskusage.yaml
  deb/openmediavault/workbench/src/app/pages/diagnostics/diagnostics-routing.module.ts
  deb/openmediavault/workbench/src/app/pages/diagnostics/diagnostics.module.ts
  deb/openmediavault/workbench/src/app/pages/diagnostics/performance-statistics/performance-statistic-df-rrd-page.component.ts
Labels: cleanup, 7.x

#1806 Show predictable device file in `Disk I/O` performance statistics tabs
  deb/openmediavault-diskstats/debian/changelog
  deb/openmediavault-diskstats/usr/share/openmediavault/engined/rpc/collectddisk.inc
  deb/openmediavault-diskstats/usr/share/openmediavault/workbench/component.d/omv-diagnostics-performance-statistics-diskio-rrd-page.yaml
Labels: enhancement, 7.x

#1810 Add Salt state for apticron
  deb/openmediavault/debian/changelog
  deb/openmediavault/debian/openmediavault.postinst
  deb/openmediavault/srv/salt/omv/deploy/apticron/default.sls
  deb/openmediavault/srv/salt/omv/deploy/apticron/files/etc-apticron-apticron_conf.j2
  deb/openmediavault/srv/salt/omv/deploy/apticron/init.sls
  deb/openmediavault/usr/share/openmediavault/engined/module/apticron.inc
Labels: enhancement, 7.x

#1812 Issue #1811: Display clamav diagnostic information in the `Diagnostics | Services | Antivirus` page
  deb/openmediavault-clamav/debian/changelog
  deb/openmediavault-clamav/debian/control
  deb/openmediavault-clamav/usr/share/openmediavault/engined/rpc/clamav.inc
  deb/openmediavault-clamav/usr/share/openmediavault/workbench/component.d/omv-diagnostics-services-clamav-text-page.yaml
  deb/openmediavault-clamav/usr/share/openmediavault/workbench/navigation.d/diagnostics.services.clamav.yaml
  deb/openmediavault-clamav/usr/share/openmediavault/workbench/route.d/diagnostics.services.clamav.yaml
Labels: enhancement, 7.x

#1817 Add UDEV rule to fix the duplicate serial number issue on Insignia NS-PCHDEDS19 devices
  deb/openmediavault/debian/changelog
  deb/openmediavault/etc/udev/rules.d/61-openmediavault-dev-disk-by-id.rules
Labels: enhancement, 7.x

#1819 Issue #1813: Return the configured mount point for each file system
  deb/openmediavault/debian/changelog
  deb/openmediavault/usr/share/openmediavault/engined/rpc/filesystemmgmt.inc
Labels: bugfix, 7.x

#1822 Support host names according to RFC1123
  deb/openmediavault/debian/changelog
  deb/openmediavault/usr/lib/python3/dist-packages/openmediavault/json/schema.py
  deb/openmediavault/usr/share/php/openmediavault/json/schema.inc
  deb/openmediavault/workbench/src/app/shared/forms/custom-validators.ts
Labels: enhancement, 7.x
